### PR TITLE
This PR add helper function.

### PR DESCRIPTION
**Pull request by minhkhoablieu**
This PR add helper function.

### CODE REVIEW

**Comment by tormjens** [comment]
Great idea! Thank you.:)

**Comment by BassemN** [comment]
@tormjens Could you please tag this change so we can start using the new helpers?

**Comment by tormjens** [comment]
@BassemN Of course! I thought I already did. Releases as v0.9.4 now :)

**Comment by BassemN** [comment]
@tormjens Many thanks

**Pull request merged**
