### PR TITLE
Updated Blade custom directives

### PR DESCRIPTION
**Pull request by bosunski**
Changed the way the $expression is used in the custom directives because it generated syntax error at compilation, but the way i updated it now fixed the problem.

### CODE REVIEW

**Comment by tormjens** [comment]
Great catch. Guess sometime in the past Laravel added ( before and ) after the expression themselves. I'll merge.

**Comment by tormjens** [comment]
Well now I will!

**Comment by bosunski** [comment]
Thanks. Your package solved a lot of problems for me. Just exactly what i'm looking for. 👍

**Comment by tormjens** [comment]
Glad to hear it ;)

**Pull request merged**
