### PR TITLE
Adds removeAction and removeFilter functions to allow removing listeners

### PR DESCRIPTION
**Pull request by mattallan**
Hey @tormjens :)

Small patch to add `removeAction` and `removeFilter` function so that listeners can be removed.

Cheers.

### CODE REVIEW

**Comment by mattallan** [comment]
I've just attached another set of `removeAllActions()` and `removeAllFilters()` functions.

I've been trying to clear the listeners collections but they're pretty locked down in protected vars. To work around that i've added new removeAll functions which allow for a hook to be passed (similarly to WP removeAll functions).

If no hook is passed the entire collection is cleared.

Look forward to getting your feedback :)

**Comment by tormjens** [comment]
Hey! This looks solid. Mind having a go at adding some tests? :)

**Comment by mattallan** [comment]
Thanks @tormjens.

I've added a bunch of unit tests to start it off :)
I've also fixed up the style issues picked up by styleci and i've also fixed up the merge conflicts.

Cheers :)

**Comment by tormjens** [comment]
You're the best! Thanks for this :) Merging.

**Pull request merged**
